### ISSUE TITLE
gtot firmware V2 trigger parameter conversion

### ISSUE THREAD

**Issue by watertien** [grand-mother/gtot#2]
The data format used by the new firmware (version. 20231130) is not properly converted by gtot.
Some branches related to the trigger parameters are empty in the .root file, e.g., **noise\_threshold_ch**, **tprev\_ch**, **post\_coincidence\_window\_ch**, etc.

And the **gps position and temperature** is not properly converted in the **tadc** and is empty in **trawvoltage**.

Most of the parameters can be found in the binary data file with the help of tools/Traces in the daq software. So it's probably a conversion issue.

**Comment by lwpiotr** [comment]
Everything should be in the trees now. However, I still need to add the new fields to DOI.
