### ISSUE TITLE
Fields not properly filled with "old structure"  option

### ISSUE THREAD

**Issue by ifleg** [grand-mother/gtot#8]
Apparently some fields in Trun trees like first_event, first_event_time, last_event, last_event_time are not correctly set when using -os option (as well as in previous gtot versions). It seems correct when using the new structure (with different root files inside a directory).

Ex: 
**With new gtot version (branch GP13_CD_update - Nov 4, 2024 - 512e25c):**
_gtot -g1 -os -i GP13_20241001_013854_RUN127_UD_RAW_ChanXYZ_20dB_12DUs_312.bin_ 
first_event: 4294967295
first_event_time : 0 (Thursday 1 January 1970 00:00:00)
last_event :  0
last_event_time : 0 (Thursday 1 January 1970 00:00:00)

_gtot -g1  -i GP13_20241001_013854_RUN127_UD_RAW_ChanXYZ_20dB_12DUs_312.bin_
first_event: 0
first_event_time : 1727746733 (Tuesday 1 October 2024 01:38:53)
last_event :  8027
last_event_time : 1727746849 (Tuesday 1 October 2024 01:40:49)

**with old version (branch fv2 - Jun 26, 2024 - 25634ab) :** 
_gtot -g1  -i GP13_20241001_013854_RUN127_UD_RAW_ChanXYZ_20dB_12DUs_312.bin_ 
first_event: 1727746850
first_event_time : 61 (Thursday 1 January 1970 00:01:01)
last_event :  858869831
last_event_time : 842019423 (Friday 6 September 1996 14:17:03)

**Comment by lwpiotr** [comment]
Complicated, but now --old_structure fills trun first/last_event(_time) from the file header, as before
